version: "3"

services:
  proxy:
    image: nginx:1.26.1-alpine
    depends_on:
      - app
    networks:
      - frontend
    ports:
      - "30080:80"
      - "30443:443"
    volumes:
      - ../data/prod/nginx:/etc/nginx
  app:
    build:
      context: ../
      dockerfile: docker/prod.Dockerfile
    image: aesterisk-web:prod
    networks:
      - frontend
      - backend
    depends_on:
      - database
    environment:
      POSTGRESQL_DB: aesterisk_prod
      POSTGRESQL_HOST: database
      POSTGRESQL_PORT: 5432
      # POSTGRESQL_USER:
      # POSTGRESQL_PASSWORD:
  database:
    image: postgres:16.3-alpine
    networks:
      - backend
    environment:
      POSTGRES_DB: aesterisk_prod
      # POSTGRES_USER:
      # POSTGRES_PASSWORD:
    volumes:
      - ../data/prod/postgresql:/var/lib/postgresql/data

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
