version: "3"

services:
  postgres:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_DB: aesterisk_dev
      POSTGRES_USER: aesterisk
      POSTGRES_PASSWORD: aesterisk
    ports:
      - "5432:5432"
    volumes:
      - ../data/dev/postgresql:/var/lib/postgresql/data
